Use UTF-8 as encoding for reading README.md
README.md uses UTF-8 characters and Python will fail to open the file
when using LC_ALL=posix:

I: pybuild base:184: python3.6 setup.py clean
Traceback (most recent call last):
  File "setup.py", line 48, in <module>
    long_desc = read('README.md')
  File "setup.py", line 35, in read
    return codecs.open(os.path.join(here, *parts), 'r').read()
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 11333: ordinal not in range(128)

Therefore enforce opening README.md always with UTF-8 encoding.

Bug-Debian: https://bugs.debian.org/872506